apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.postgres.fullname" . }}-initdb-scripts
  namespace: default
  labels:
    {{- include "charts.postgres.labels" . | nindent 4 }}
data:
  "01-create-databases.sql": |
{{ .Files.Get "files/01-create-databases.sql" | indent 4 }}
