apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.postgres.fullname" . }}
  labels:
    {{- include "charts.postgres.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "charts.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "charts.postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: initdb-scripts
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
          resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
        - name: postgres-storage
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "charts.postgres.fullname" . }}-pvc
      {{- else }}
          emptyDir: {}
      {{- end }}
        - name: initdb-scripts
          configMap:
            name: {{ include "charts.postgres.fullname" . }}-initdb-scripts
