apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.postgres.fullname" . }}
  labels:
    {{- include "charts.postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "charts.postgres.selectorLabels" . | nindent 4 }}
