name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

#      - name: Run API Tests
#        uses: matt-ball/newman-action@master
#        with:
#          collection: <variant>/postman/collection.json
#          environment: <variant>/postman/environment.json
#          delayRequest: 100
#          reporters: '[ "cli" ]'
#
#      - uses: education/autograding@v1
#        id: autograder
#        continue-on-error: true
#
#      - name: Github auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
#          homework_number: 5
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"
      - name: Setup Go 1.24.3
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'


      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d


      - name: Run Unit Tests
        run: |
          cd src/rating-system && go test ./internal/service/...
          cd ../reservation-system && go test ./internal/service/...
          cd ../library-system && go test ./internal/service/...

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli"]'


      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v